services:
  # Service untuk Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    # working_dir: /var/www
    volumes:
      - .:/var/app
      - /app/node_modules
    networks:
      - laravel-network
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - db

  # Service untuk database (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: putar_putar_film           # Nama database sesuai dengan DB_DATABASE di .env                     # User MySQL sesuai dengan DB_USERNAME di .env
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   
      MYSQL_ROOT_PASSWORD: ""              # Password sesuai dengan DB_PASSWORD di .env (kosongkan jika tidak ada password)
    ports:
      - "3306:3306"                          # Port MySQL
    networks:
      - laravel-network
    volumes:
      - db_data:/var/lib/mysql
      - ./putarfilm.sql:/docker-entrypoint-initdb.d/putarfilm.sql

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data: