version: '3.8'

services:
  # Service untuk Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    ports:
      - "8000:9000"  # Akses web Laravel melalui port 8000 di host
    environment:
      - APP_ENV=local
      - APP_KEY=base64:b3eLDp9dAf8Jxo0AcZFNeHKOUNq9Dwl4gqxarHDqZV0=
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=putarfilm
      - DB_USERNAME=root
      - DB_PASSWORD=
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - CACHE_STORE=database
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=db
      - REDIS_PORT=6379
      - MAIL_MAILER=log
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME="${APP_NAME}"

  # Service untuk database (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # Password root untuk MySQL
      MYSQL_DATABASE: putarfilm             # Nama database sesuai dengan DB_DATABASE di .env
      MYSQL_USER: root                      # User MySQL sesuai dengan DB_USERNAME di .env
      MYSQL_PASSWORD: ""                    # Password sesuai dengan DB_PASSWORD di .env (kosongkan jika tidak ada password)
    ports:
      - "8000:8000"                          # Port MySQL
    networks:
      - laravel-network

  # Service untuk Redis (opsional, jika digunakan di aplikasi Laravel)
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "8000:8000"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge